"""sitemap.xml, regenerated by the daily run so lastmod is never a lie.

A stale lastmod is worse than none: Google learns to distrust it and crawls
less often, which is the opposite of what a calendar that changes every morning
wants.
"""

from __future__ import annotations

import os

SITE = "https://shinabarger.github.io/kid-events-in-ann-arbor/"


def sitemap_xml(lastmod: str) -> str:
    day = (lastmod or "")[:10]
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        "  <url>\n"
        f"    <loc>{SITE}</loc>\n"
        + (f"    <lastmod>{day}</lastmod>\n" if day else "")
        + "    <changefreq>daily</changefreq>\n"
        "    <priority>1.0</priority>\n"
        "  </url>\n"
        "</urlset>\n"
    )


def write_sitemap(out_dir: str, lastmod: str) -> str:
    path = os.path.join(out_dir, "sitemap.xml")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(sitemap_xml(lastmod))
    return path
