"""sitemap.xml, regenerated by the daily run so lastmod is never a lie.

A stale lastmod is worse than none: Google learns to distrust it and crawls
less often, which is the opposite of what a calendar that changes every morning
wants.
"""

from __future__ import annotations

import os

SITE = "https://shinabarger.github.io/kid-events-in-ann-arbor/"


PAGES = [
    ("", "daily", "1.0"),
    ("about.html", "monthly", "0.5"),
]


def sitemap_xml(lastmod: str) -> str:
    day = (lastmod or "")[:10]
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for path, changefreq, priority in PAGES:
        out.append("  <url>")
        out.append(f"    <loc>{SITE}{path}</loc>")
        if day:
            out.append(f"    <lastmod>{day}</lastmod>")
        out.append(f"    <changefreq>{changefreq}</changefreq>")
        out.append(f"    <priority>{priority}</priority>")
        out.append("  </url>")
    out.append("</urlset>")
    return "\n".join(out) + "\n"


def write_sitemap(out_dir: str, lastmod: str) -> str:
    path = os.path.join(out_dir, "sitemap.xml")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(sitemap_xml(lastmod))
    return path
